### ISSUE TITLE
Dockerize circleci dependencies (wivet, sqlmap test env, etc.)

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#11353]
- [x] Dockerize circleci dependencies
   - [x] django-moth
   - [x] WIVET
   - [x] wavsep (blocked - not enough java knowledge)
   - [x] php-moth
   - [x] sqlmap-testenv
 - [x] Create a docker-compose to run all images
 - [x] Wiki / documentation for this

**Comment by andresriancho** [comment]
These lines should be removed at the end, since all will be running in docker:
```yaml
  # This is required to run WIVET
  php:
    version: 5.5.11

  java:
    version: oraclejdk7
```
