### ISSUE TITLE
Enhance the OpenAPI plugin to accept user-provided values for parameters

### ISSUE THREAD

**Issue by artem-smotrakov** [andresriancho/w3af#17315]
While generating fuzzable requests for API endpoints, the OpenAPI plugin tries to find good values for the parameters which are accepted by the API endpoints. The plugin considers default values provided in the OpenAPI spec, or tries to guess the best value based on parameter name, type, format, etc. I think this is a very good approach for an initial scan but it may not be enough if we want to test an application a bit deeper. The problem is that there is not an easy way to let the plugin know about values it should use for testing. Let's consider the following API endpoint:

```
paths:
  /users/{userId}:
    post:
      summary: Update user
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
        - in: header
          name: X-User-Name
          schema:
            type: string
          required: true
          description: User name
```

In this case, the OpenAPI plugin creates a fuzzable request which assigns some pre-defined number (for example, 42) to `userId` and some pre-defined string to `X-User-Name`. The plugin tries its best when guessing valid values, but it has no idea about the actual context. When w3af tries to fuzz `X-User-Name`, it will send requests to `/users/42`. Most probably the requests will be rejected if no used exists with this ID. As a result, w3af won't actually test how the application processes the `X-User-Name` header.

I would like to propose adding a way how a user can provide a list of valid values for specific parameters for API endpoints. Currently I don't see the plugin provides such a way. The feature would help to use w3af in a better and more efficient way for:

- grey-box testing when a tester already has some knowledge about the application
- regular testing applications in CI/CD

There are only a couple of workarounds which are not flexible:

- use custom API spec which defines single default values
- use `headers_file -> header_file` option to set pre-defined headers

I think it would be much better if a user could provide a list of meaningful values for a particular parameter. Basically, a user needs to specify a mapping `{path, parameter_name} -> [ list of values ]`

I can implement such a feature if it gets a positive feedback. Before opening a pull request, I'd like to agree on a way how a user can provide such values. I would add `parameter_values` option for the OpenAPI plugin. The option should contain a path to a file which contains `{path, parameter_name} -> [ list of values ]` mapping. The file may be in JSON, YAML or CSV format. I'd start with JSON or YAML.

Please let me know what you think.
